### ISSUE TITLE
[R] R Package Installation in Ubuntu

### ISSUE THREAD

**Issue by Yunrui** [dmlc/mxnet#1057]
hi folks,

I managed to install mxnet in OS X before but failed in ubuntu when doing "R CMD INSTALL mxnet_0.5.tar.gz". Error message is listed at the bottom. 
It seems to me that some env variable should be set. Then I did set LD_LIBRARY_PATH and DYLD_LIBRARY_PATH to where my libcudart.so.7.5 stays. But no luck, same error. 

what's the next step to troubleshoot? I remember in OS X, it has otool to check link information and install_name_tool to change location? anything similar in ubuntu? Thanks in advance! 

======= ENVIRONMENT VARIABLE=======
echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64

======= ERROR MESSAGE ============
installing to /usr/local/lib/R/site-library/mxnet/libs
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'mxnet', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: 无法载入共享目标对象‘/usr/local/lib/R/site-library/mxnet/libs/libmxnet.so’：:
  libcudart.so.7.5: 无法打开共享对象文件: 没有那个文件或目录
错误: 载入失败
停止执行
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/mxnet’

**Comment by thirdwing** [comment]
I think we have the same environment variable and it works on my machine.

```
~$ echo $LD_LIBRARY_PATH
/usr/local/cuda-7.5/lib64
```

Have you ever tried to compile and run any cuda examples?

**Comment by Yunrui** [comment]
I tried several samples in CUDA folder, it works well.

**Comment by Yunrui** [comment]
BTW, I used ldd to check dependencies in libmxnet.so, and pretty sure the required file is in right location.

me:~/mxnet/R-package/inst/libs$ ldd libmxnet.so | grep libcudart.so
	libcudart.so.7.5 => /usr/local/cuda-7.5/lib64/libcudart.so.7.5 (0x00007f53665e1000)

me:~/mxnet/R-package/inst/libs$ ls -l /usr/local/cuda-7.5/lib64/libcudart.so.7.5
lrwxrwxrwx 1 root root 19 Aug 15 23:55 /usr/local/cuda-7.5/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18

**Comment by Yunrui** [comment]
I tried python mnist gpu case, it works well. So I think my cuda and mxnet build are well made. 

Then I went into R. After checked Sys.getEnv, the cuda folder is not in the list. Then I do Sys.setEnv, works.

**Comment by howardlinus** [comment]
@Yunrui, I have a very similar problem, can you tell me what exactly you have done to make it wok? thanks

**Comment by tornadomeet** [comment]
@Yunrui  I met the same problem, but not solved, just as ```Sys.setenv(CUDA_LIB_PATH="/usr/local/cuda/lib64")```, so what's the name you seted in Sys.setenv()?
