### ISSUE TITLE
Low GPU utilization on multi-GPU training

### ISSUE THREAD

**Issue by shenxiul** [dmlc/mxnet#1467]
I'm trying to use mxnet on a node with 16 CPUs (Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz) and 8 GPUs (GeForce GTX TITAN X). When trying to train LeNet on MNIST, I got single GPU throughput at Speed: 18691.98 samples/sec, for two GPU, the speed down to 11807.86 samples/sec, and using more GPU gives me an even lower speed (8 GPU: 4852.14 samples/sec). I tried different batch sizes and different models and performance issues about the same. Using nvidia-smi I see that the "Volatile
GPU-Util" section actually adds up to 100%, no matter how many GPUs I am using. If I train different models separately, I can fill up all GPUs close to 100%. I compiled mxnet with CUDA 7.5, cuDNN v3, MKL(2013), with openmp support, and my system is RHEL6. Is this my compilation issue or mxnet issue? Thanks!

**Comment by yuzcccc** [comment]
Try other larger dataset such as cifar10 or imagenet

**Comment by shenxiul** [comment]
Hi @yuzcccc, yes I tried cifar10 with inception and ResNet with different batch_size (128, 256, 512) and problem remains the same. In every case  the Volatile GPU-Util adds up to 100% only.

**Comment by shenxiul** [comment]
I resolved this issue, it was a cluster problem rather than mxnet's problem. Sorry.
