### ISSUE TITLE
got error when setting dilate>1 in convolution layer(only in Cudnn)

### ISSUE THREAD

**Issue by ascust** [dmlc/mxnet#1645]
I set a layer's dilate=(2,2), but I got this error. 
```
[18:47:57] /home/shentong/mxnet/dmlc-core/include/dmlc/logging.h:241: [18:47:57] src/operator/./cudnn_convolution-inl.h:265: Check failed: (cudnnGetConvolutionBackwardDataWorkspaceSize(s->dnn_handle_, filter_desc_, out_desc_, conv_desc_, in_desc_, back_algo_, &back_size)) == (CUDNN_STATUS_SUCCESS) 
[18:47:57] /home/shentong/mxnet/dmlc-core/include/dmlc/logging.h:241: [18:47:57] src/engine/./threaded_engine.h:295: [18:47:57] src/operator/./cudnn_convolution-inl.h:265: Check failed: (cudnnGetConvolutionBackwardDataWorkspaceSize(s->dnn_handle_, filter_desc_, out_desc_, conv_desc_, in_desc_, back_algo_, &back_size)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:47:57] src/engine/./threaded_engine.h:295: [18:47:57] src/operator/./cudnn_convolution-inl.h:265: Check failed: (cudnnGetConvolutionBackwardDataWorkspaceSize(s->dnn_handle_, filter_desc_, out_desc_, conv_desc_, in_desc_, back_algo_, &back_size)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)
```
When I set it back to (1,1), it is gone. And important thing is when I did not use Cudnn, it was ok also. So it seems the problem happens when dilate>1 and using cudnn.

**Comment by ascust** [comment]
And also, I found when using dilate>1, the size is not guessed correctly. For example, I have a 3x3 kernel and stride 1 with no padding. If there is an image with 64x64 and I use dilate=(3,3), the result is 57x57. In my opinion it should be 58x58. It should be imagesize-(dilate*2+1)+1 in this case. Is it right? @tqchen @piiswrong

**Comment by piiswrong** [comment]
Cudnn doesn't support dilate

**Comment by ascust** [comment]
Does the cudnn library has the interface? I did not see anything that looks like this parameter.

**Comment by kadeng** [comment]
If you want to, try this:
https://github.com/kadeng/mxnet/commit/1dfa3516074b633cadcfeecd5764b5a4de8b938f

It should force the usage of the non CuDNN Convolution operator. I don't have time right now to merge it properly into the feature branch I created for https://github.com/dmlc/mxnet/issues/1457 but it's easy enough..

**Comment by ascust** [comment]
Thanks , it helped a lot.
