### ISSUE TITLE
model prediction fail

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#2371]
I can fit my model normally, but when I try to predict I get this error:

```
[11:24:44] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:24:44] src/operator/./cudnn_batch_norm-inl.h:138: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
[11:24:44] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:24:44] src/engine/./threaded_engine.h:306: [11:24:44] src/operator/./cudnn_batch_norm-inl.h:138: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:24:44] src/engine/./threaded_engine.h:306: [11:24:44] src/operator/./cudnn_batch_norm-inl.h:138: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
```

This is a very new error for me as I've been able to make predictions recently. I'm using cuDNN v5, cuda v5.0. The last time I pulled was a few weeks ago, but I've been able to run it successfully since then. Any idea what the issue could be?

**Comment by jmschrei** [comment]
The code looks basically like this:

```Python
	X_train = TrainingGenerator(train_sequence, train_dnases, train_contacts, train_regions, window, data_shapes, coord, batch_size)
	X_eval = ValidationGenerator(valid_sequence, valid_dnases, valid_contacts, valid_regions, window, data_shapes, coord, batch_size)

	model = Rambutan( use_coord=coord,
		              ctx=[mx.gpu(0), mx.gpu(1), mx.gpu(2), mx.gpu(3)], 
					  epoch_size=5000,
					  num_epoch=1,
					  learning_rate=0.01,
					  wd=0.000,
					  optimizer='adam'
					)

	model.fit( X=X_train,
			   eval_metric=['acc', roc_auc_score],
			   batch_end_callback=mx.callback.Speedometer(batch_size)
			)

	y = model.predict(X_eval)[:,1]
	numpy.save('rambutan-q={}.npy'.format(q), y)
```

If I put eval_data = X_eval into the fit step, it seems to work. The issue is the predict step.

**Comment by Godricly** [comment]
is cudnn compatible with cuda5.0?

**Comment by piiswrong** [comment]
so it fails at this line `cudnn_batch_norm-inl.h:138: Check failed: (cudnnBatchNorma`
I would try printing out the return value ( currently it only compare it agains success) and look it up in cudnn's manual

**Comment by Godricly** [comment]
Check your eps value if it is within cudnn limit.
I just got an error alike on line 123 when I'm trying resnet in example. I print out the return value of CUDNN_STATUS_BAD_PARAM. So I add it a little bit(1e-9), now it works.

**Comment by Answeror** [comment]
This may also caused by a large `batch_size` (although the memory usage may be quite low), try a smaller one.
