### ISSUE TITLE
OSError: libcudart.so.7.0: cannot open shared object file

### ISSUE THREAD

**Issue by csucat** [dmlc/mxnet#2845]
I am using CentOS 7 with cuda 7.5 and cudnn v5.  Openblas is used as the blas library and opencv was installed using yum.  some of configure setting related to these is:
```
ADD_LDFLAGS =-L/usr/local/cudnn-v5/lib64 -L/usr/lib64
ADD_CFLAGS =-I/usr/local/cudnn-v5/include
USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda
USE_CUDNN = 1
USE_BLAS = openblas
USE_OPENCV = 1
```
`make -j32` gives no error message.  But when I try to run the code in the example/image-classification directory, it give the error:
```
 python example/image-classification/train_mnist.py
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/jdhao/local/mxnet/example/image-classification/find_mxnet.py", line 2, in <module>
    import mxnet as mx
  File "/home/jdhao/.local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/jdhao/.local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/jdhao/.local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/home/jdhao/anaconda2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/jdhao/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.7.0: cannot open shared object file: No such file or directory
```

And yes, I have added the cuda runtime library to my .bash_profile, it is 
```
 export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
```
Is there anything wrong with my compilation or settings?

**Comment by wshenx** [comment]
you can try the following script from bash
     `ldconfig /usr/local/cuda/lib64 `

**Comment by csucat** [comment]
@wshenx , I  tried, but still got the same error message. Where I can find a complete config.mk file? Maybe that will help me find what is wrong.

**Comment by Ldpe2G** [comment]
if you are using cuda 7.5, shouldn't it be libcudart.so.7.5?

**Comment by wshenx** [comment]
@csucat Well, I don't think it has anything to do with your compilation since `make` reports no error.  As @Ldpe2G suggests, it is strange that python requires the 7.0 version of the lib instead of 7.5. You can check that first.

**Comment by wshenx** [comment]
@csucat At a second thought, if you are using the latest Mxnet, the python version should not be version 0.5. Maybe 0.7 or higher, I'm not quite sure. I think you previously installed a older version of mxnet python wrapper and at that time cuda 7.0 was installed on your system. So I suggest you to reinstall your python wrapper again so your `site-packages` can be updated.

**Comment by csucat** [comment]
@wshenx yeah, I have installed mxnet when the server was using the cuda7.0 drivers, and then the cuda 7.5 driver was installed and the cuda 7.0 driver was removed.  I deleted the mxnet root directory and download the mxnet project again according to the install instructions(`git clone --recursive https://github.com/dmlc/mxnet`). By the way, originally, I use the system-provided python when I was compiling the mxnet package, but now I am using Anaconda.

**Comment by wshenx** [comment]
yeah, a fresh new installation usually helps~

**Comment by csucat** [comment]
@wshenx, Problem Solved!!  I thought the system-provided python and anaconda have nothing to with each other.  Apparently I was wrong. The output of `conda list | grep mxnet` only shows that mxnet version 0.7 was installed. But when I use `pip uninstall mxnet`(this pip is from anaconda), surprisingly,  mxnet version 0.5 was uninstalled. Using the command again uninstalled the mxnet version 0.7.  Finally, reinstalling mxnet python wrapper solved the problem.

**Comment by csucat** [comment]
For anyone who has met this problem: make sure that any previous install of mxnet wrapper is removed and then reinstall the new mxnet wrapper.
