### ISSUE TITLE
cudnn error when compiling

### ISSUE THREAD

**Issue by chenjx1005** [dmlc/mxnet#3102]
the compiler works well when I use the mxnet downloaded at 20th, Jun. However when I use the latest mxnet, the complier has this error:
`src/operator/./cudnn_convolution-inl.h:400:56: error: too many arguments to function 'cudnnStatus_t cudnnSetConvolutionNdDescriptor(cudnnConvolutionDescriptor_t, int, const int*, const int*, const int*, cudnnConvolutionMode_t)'
                                                  dtype_), CUDNN_STATUS_SUCCESS);`

**Comment by piiswrong** [comment]
what's your cudnn version? Try update to 5.0 or 5.1

**Comment by chenjx1005** [comment]
I don't know how to print the version of CUDNN. The lib file of my cudnn is `libcudnn.so.7.0.64`

**Comment by chenjx1005** [comment]
my original  cudnn version is 3.0. After update to 5.0 the problem solved. Thank you.
