### ISSUE TITLE
Can't use GPU?

### ISSUE THREAD

**Issue by QuantumLiu** [dmlc/mxnet#3748]
I'm using Ubuntu16.04,gtx1060,cuda8.0,cudnnv5.1
My Theano and TF worked well with GPU.
I have complied config.mk,and got following(last several lines)
====================================
```
a - build/src/resource.o
a - build/src/io/io.o
a - build/src/io/image_aug_default.o
a - build/src/io/iter_csv.o
a - build/src/io/iter_image_recordio.o
a - build/src/io/iter_mnist.o
a - build/src/common/mxrtc.o
a - build/src/ndarray/ndarray_function.o
a - build/src/ndarray/ndarray.o
a - build/src/optimizer/sgd.o
a - build/src/optimizer/optimizer.o
a - build/src/operator/loss_binary_op.o
a - build/src/operator/block_grad.o
a - build/src/operator/smooth_l1_unary.o
a - build/src/operator/fully_connected.o
a - build/src/operator/pooling.o
a - build/src/operator/cast.o
a - build/src/operator/activation.o
a - build/src/operator/crop.o
a - build/src/operator/spatial_transformer.o
a - build/src/operator/cudnn_convolution.o
a - build/src/operator/swapaxis.o
a - build/src/operator/pad.o
a - build/src/operator/batch_norm.o
a - build/src/operator/softmax_output.o
a - build/src/operator/matrix_op.o
a - build/src/operator/operator_util.o
a - build/src/operator/sequence_reverse.o
a - build/src/operator/rnn.o
a - build/src/operator/operator.o
a - build/src/operator/svm_output.o
a - build/src/operator/sequence_last.o
a - build/src/operator/elementwise_binary_op.o
a - build/src/operator/l2_normalization.o
a - build/src/operator/lrn.o
a - build/src/operator/correlation.o
a - build/src/operator/elementwise_binary_scalar_op.o
a - build/src/operator/sequence_mask.o
a - build/src/operator/reshape.o
a - build/src/operator/broadcast_reduce_op.o
a - build/src/operator/instance_norm.o
a - build/src/operator/native_op.o
a - build/src/operator/embedding.o
a - build/src/operator/identity_attach_KL_sparse_reg.o
a - build/src/operator/elementwise_binary_broadcast_op.o
a - build/src/operator/upsampling.o
a - build/src/operator/deconvolution.o
a - build/src/operator/elementwise_sum.o
a - build/src/operator/convolution.o
a - build/src/operator/cudnn_batch_norm.o
a - build/src/operator/cross_device_copy.o
a - build/src/operator/elementwise_unary_op.o
a - build/src/operator/regression_output.o
a - build/src/operator/make_loss.o
a - build/src/operator/ndarray_op.o
a - build/src/operator/concat.o
a - build/src/operator/leaky_relu.o
a - build/src/operator/sample_op.o
a - build/src/operator/roi_pooling.o
a - build/src/operator/custom.o
a - build/src/operator/slice_channel.o
a - build/src/operator/dropout.o
a - build/src/operator/broadcast_mask_op.o
a - build/src/operator/softmax_activation.o
a - build/src/symbol/graph_memory_allocator.o
a - build/src/symbol/graph_executor.o
a - build/src/symbol/static_graph.o
a - build/src/symbol/symbol.o
a - build/src/engine/naive_engine.o
a - build/src/engine/threaded_engine_pooled.o
a - build/src/engine/engine.o
a - build/src/engine/threaded_engine.o
a - build/src/engine/threaded_engine_perdevice.o
a - build/src/storage/storage.o
a - build/src/c_api/c_predict_api.o
a - build/src/c_api/c_api.o
a - build/src/c_api/c_api_error.o
a - build/src/kvstore/kvstore.o
a - build/src/operator/mkl/mkl_cppwrapper.o
a - build/src/operator/mkl/mkl_memory.o
a - build/src/ndarray/ndarray_function_gpu.o
a - build/src/optimizer/sgd_gpu.o
a - build/src/operator/correlation_gpu.o
a - build/src/operator/svm_output_gpu.o
a - build/src/operator/fully_connected_gpu.o
a - build/src/operator/elementwise_binary_scalar_op_gpu.o
a - build/src/operator/sequence_mask_gpu.o
a - build/src/operator/lrn_gpu.o
a - build/src/operator/reshape_gpu.o
a - build/src/operator/swapaxis_gpu.o
a - build/src/operator/pooling_gpu.o
a - build/src/operator/regression_output_gpu.o
a - build/src/operator/block_grad_gpu.o
a - build/src/operator/leaky_relu_gpu.o
a - build/src/operator/embedding_gpu.o
a - build/src/operator/identity_attach_KL_sparse_reg_gpu.o
a - build/src/operator/broadcast_reduce_op_gpu.o
a - build/src/operator/loss_binary_op_gpu.o
a - build/src/operator/roi_pooling_gpu.o
a - build/src/operator/cudnn_batch_norm_gpu.o
a - build/src/operator/native_op_gpu.o
a - build/src/operator/elementwise_unary_op_gpu.o
a - build/src/operator/convolution_gpu.o
a - build/src/operator/make_loss_gpu.o
a - build/src/operator/batch_norm_gpu.o
a - build/src/operator/upsampling_gpu.o
a - build/src/operator/concat_gpu.o
a - build/src/operator/dropout_gpu.o
a - build/src/operator/softmax_activation_gpu.o
a - build/src/operator/pad_gpu.o
a - build/src/operator/slice_channel_gpu.o
a - build/src/operator/l2_normalization_gpu.o
a - build/src/operator/smooth_l1_unary_gpu.o
a - build/src/operator/elementwise_binary_broadcast_op_gpu.o
a - build/src/operator/elementwise_sum_gpu.o
a - build/src/operator/cast_gpu.o
a - build/src/operator/crop_gpu.o
a - build/src/operator/sequence_reverse_gpu.o
a - build/src/operator/spatial_transformer_gpu.o
a - build/src/operator/deconvolution_gpu.o
a - build/src/operator/elementwise_binary_op_gpu.o
a - build/src/operator/softmax_output_gpu.o
a - build/src/operator/sample_op_gpu.o
a - build/src/operator/broadcast_mask_op_gpu.o
a - build/src/operator/instance_norm_gpu.o
a - build/src/operator/matrix_op_gpu.o
a - build/src/operator/sequence_last_gpu.o
a - build/src/operator/rnn_gpu.o
a - build/src/operator/activation_gpu.o
========================================
When use mxnet:
======================
a = mx.nd.ones((2, 3),
... mx.gpu())
[14:02:51] /home/quantumliu/MXNet/mxnet/dmlc-core/include/dmlc/./logging.h:235: [14:02:51] src/storage/storage.cc:78: Compile with USE_CUDA=1 to enable GPU usage
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 894, in ones
    arr = empty(shape, ctx, dtype)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 611, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 69, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:02:51] src/storage/storage.cc:78: Compile with USE_CUDA=1 to enable GPU usage
```
============
And my config.mk:
============
```
export CC = gcc
export CXX = g++
export NVCC = nvcc

# whether compile with debug
DEBUG = 0

# the additional link flags you want to add
ADD_LDFLAGS =

# the additional compile flags you want to add
ADD_CFLAGS =

#---------------------------------------------
# matrix computation libraries for CPU/GPU
#---------------------------------------------

# whether use CUDA during compile
USE_CUDA = 1

# add the path to CUDA library to link and compile flag
# if you have already add them to environment variable, leave it as NONE
# USE_CUDA_PATH = /usr/local/cuda
USE_CUDA_PATH = /usr/local/cuda

# whether use CuDNN R3 library
USE_CUDNN = 1

# whether use cuda runtime compiling for writing kernels in native language (i.e. Python)
USE_NVRTC = 0

# whether use opencv during compilation
# you can disable it, however, you will not able to use
# imbin iterator
USE_OPENCV = 1

# use openmp for parallelization
USE_OPENMP = 1

# whether use MKL2017 library
USE_MKL2017 = 0

# whether use MKL2017 experimental feature for high performance
USE_MKL2017_EXPERIMENTAL = 0

# choose the version of blas you want to use
# can be: mkl, blas, atlas, openblas
# in default use atlas for linux while apple for osx
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

# add path to intel library, you may need it for MKL, if you did not add the path
# to environment variable
USE_INTEL_PATH = NONE

# If use MKL, choose static link automatically to allow python wrapper
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

#----------------------------
# Settings for power and arm arch
#----------------------------
ARCH := $(shell uname -a)
ifneq (,$(filter $(ARCH), armv6l armv7l powerpc64le ppc64le))
	USE_SSE=0
else
	USE_SSE=1
endif

#----------------------------
# distributed computing
#----------------------------

# whether or not to enable multi-machine supporting
USE_DIST_KVSTORE = 0

# whether or not allow to read and write HDFS directly. If yes, then hadoop is
# required
USE_HDFS = 0

# path to libjvm.so. required if USE_HDFS=1
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

# whether or not allow to read and write AWS S3 directly. If yes, then
# libcurl4-openssl-dev is required, it can be installed on Ubuntu by
# sudo apt-get install -y libcurl4-openssl-dev
USE_S3 = 0

#----------------------------
# additional operators
#----------------------------

# path to folders containing projects specific operators that you don't want to put in src/operators
EXTRA_OPERATORS =


#----------------------------
# plugins
#----------------------------

# whether to use caffe integration. This requires installing caffe.
# You also need to add CAFFE_PATH/build/lib to your LD_LIBRARY_PATH
# CAFFE_PATH = $(HOME)/caffe
# MXNET_PLUGINS += plugin/caffe/caffe.mk

# whether to use torch integration. This requires installing torch.
# You also need to add TORCH_PATH/install/lib to your LD_LIBRARY_PATH
# TORCH_PATH = $(HOME)/torch
# MXNET_PLUGINS += plugin/torch/torch.mk

# WARPCTC_PATH = $(HOME)/warp-ctc
# MXNET_PLUGINS += plugin/warpctc/warpctc.mk

# whether to use sframe integration. This requires build sframe
# git@github.com:dato-code/SFrame.git
# SFRAME_PATH = $(HOME)/SFrame
# MXNET_PLUGINS += plugin/sframe/plugin.mk
```

**Comment by piiswrong** [comment]
make clean && make

**Comment by QuantumLiu** [comment]
Well, i have fixed it by install for python again.
Thank you for help!
