### ISSUE TITLE
issue with enabling CUDA

### ISSUE THREAD

**Issue by ferodia** [dmlc/mxnet#435]
Hello,
I'm trying to enable CUDA compiling in order to use gpu by changing the value in config.mx of USE_CODA but I keep getting this error:

g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -c src/engine/naive_engine.cc -o build/engine/naive_engine.o
g++ -std=c++0x -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -MM -MT build/engine/threaded_engine.o src/engine/threaded_engine.cc >build/engine/threaded_engine.d
g++ -std=c++0x -c -DMSHADOW_FORCE_STREAM -Wall -O3 -I./mshadow/ -I./dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/opt/cuda/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -c src/engine/threaded_engine.cc -o build/engine/threaded_engine.o
In file included from src/engine/threaded_engine.cc:14:0:
src/engine/../common/cuda_utils.h: In function ‘const char* mxnet::common::cuda::CublasGetErrorString(cublasStatus_t)’:
src/engine/../common/cuda_utils.h:44:10: error: ‘CUBLAS_STATUS_NOT_SUPPORTED’ was not declared in this scope
     case CUBLAS_STATUS_NOT_SUPPORTED:
          ^
make: *** [build/engine/threaded_engine.o] Erreur 1

I didn't manage to find out what I am doing wrong. 
Thanks in advance for your help

**Comment by piiswrong** [comment]
Did you add your cuda include and lib path to config.mk?

**Comment by tqchen** [comment]
We require the /path/to/cuda/include to be in include search path and /path/to/cuda/lib to be in library path

**Comment by ferodia** [comment]
everything was included but I was using an old version of CUDA (4.4) . after upgrade to 7.5 the issue seems to be gone !
I could compile and reinstall.
Thanks a lot
