### ISSUE TITLE
multi-machine distributed-training hang out

### ISSUE THREAD

**Issue by Jellyrick** [dmlc/mxnet#606]
i wan't to use multi machine to train imagenet. all machine have a shared file system.
when server_nodes is 1, all going well on every machine.  
But when server_nodes bigger than 1, the process is stuck

hosts:
192.168.1.200
192.168.1.201

i run below command on 192.168.1.200:
../../tracker/dmlc_mpi.py -n 2 -s 2 -H hosts python train_imagenet.py

only print :

mpirun -n 2  -env DMLC_ROLE server -env DMLC_PS_ROOT_PORT 9795 -env DMLC_PS_ROOT_URI 127.0.0.1 -env DMLC_NUM_SERVER 2 -env DMLC_NUM_WORKER 2 --hostfile hosts python train_imagenet.py
mpirun -n 2  -env DMLC_ROLE worker -env DMLC_PS_ROOT_PORT 9795 -env DMLC_PS_ROOT_URI 127.0.0.1 -env DMLC_NUM_SERVER 2 -env DMLC_NUM_WORKER 2 --hostfile hosts python train_imagenet.py

and 
htop on 192.168.1.201, i can find two  python  train_imagenet.py

============================================

how can i solve this problem?

**Comment by mli** [comment]
the problem is because the scheduler or the root node uses the wrong IP (127.0.0.1) which cannot be reached by others, the codes are there 

https://github.com/dmlc/ps-lite/blob/dev/tracker/tracker.py#L384

**Comment by Jellyrick** [comment]
@mli ，problem solved！

another question：

how can i use  0，1gpu in machine 0， and  0，3gpu in machine 1， thxs

**Comment by mli** [comment]
```python
if kv.rank == 0:
   devs = [mx.gpu(0), mx.gpu(1)]
else:
   devs = [mx.gpu(0), mx.gpu(3)]

mode = mx.model.FeedForward(ctx=devs, ...)
```

**Comment by Jellyrick** [comment]
@mli  I am confused about the relationship between  machine and server && server and worker. what's the design philosophy?  If i have multi machine, how many server-nodes should run?

**Comment by mli** [comment]
you can simple use number workers = num servers = num machines

**Comment by Jellyrick** [comment]
another question:

if use 3 gpu in machine0 and use  1 gpu in machine 1,  with 2 works 2 servers。

the param 'batch_size' in mx.io.ImageRecordIter should be assign what?

**Comment by mli** [comment]
if the gpus are identical, you can fix a batch size of each gpu, say 48, then `batch_size = 48 * num_gpus_on_this_machine.`. otherwise please refer to PR #566
