### ISSUE TITLE
Segmentation Fault when training in batches v0.10

### ISSUE THREAD

**Issue by nikrao** [dmlc/mxnet#6667]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.10.0

Python version and distribution: 2.7

## Error Message:
loading data
X
Y
[New Thread 0x7ffff0b9d700 (LWP 4558)]
[New Thread 0x7ffff339e700 (LWP 4559)]
[New Thread 0x7ffff3b9f700 (LWP 4560)]
[New Thread 0x7fff803ab700 (LWP 4561)]
[New Thread 0x7fff6a238700 (LWP 4562)]
iterator made
binding
[New Thread 0x7fff69a37700 (LWP 4563)]
[New Thread 0x7fff69236700 (LWP 4564)]
[New Thread 0x7fff63db1700 (LWP 4565)]
[New Thread 0x7fff631df700 (LWP 4567)]
[New Thread 0x7fff629de700 (LWP 4568)]
starting to train
[22:20:25] /home/ubuntu/src/mxnet/dmlc-core/include/dmlc/logging.h:304: [22:20:25] /home/ubuntu/src/mxnet/mshadow/mshadow/./stream_gpu-inl.h:102: Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0) Create cublas handle failed

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fffe12a5fdc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(+0x105cfaa) [0x7fffe1c96faa]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0xa7) [0x7fffe1c9af17]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7fffc4dc3a60]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ffff7bc4184]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ffff78f1bed]

[22:20:25] /home/ubuntu/src/mxnet/dmlc-core/include/dmlc/logging.h:304: [22:20:25] /home/ubuntu/src/mxnet/mshadow/mshadow/./stream_gpu-inl.h:102: Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0) Create cublas handle failed

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fffe12a5fdc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(+0x105cfaa) [0x7fffe1c96faa]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0xa7) [0x7fffe1c9af17]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7fffc4dc3a60]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ffff7bc4184]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ffff78f1bed]

terminate called after throwing an instance of 'dmlc::Error'
terminate called recursively
  what():  [22:20:25] /home/ubuntu/src/mxnet/mshadow/mshadow/./stream_gpu-inl.h:102: Check failed: err == CUBLAS_STATUS_SUCCESS (1 vs. 0) Create cublas handle failed

Stack trace returned 6 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fffe12a5fdc]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(+0x105cfaa) [0x7fffe1c96faa]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0xa7) [0x7fffe1c9af17]
[bt] (3) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb1a60) [0x7fffc4dc3a60]
[bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ffff7bc4184]
[bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ffff78f1bed]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff69a37700 (LWP 4563)]
0x00007ffff782ac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 

### DETAILED INFORMATION:
I am running an experiment using the Deep Learning AMI Ubuntu (p2 machine).

I was running the code before the latest release of MXNet, and it was working fine. However, it returns segmentation faults when I do the following:

for b in tr_iter:
model.forward(b, is_train=True)
model.backward()
model.update()

The error occurs in the model.forward() part itself

tr_iter is the training data iterator, with each batch of data being 128 X 21494 size

model
<mxnet.module.module.Module at 0x7fa04c595590>

model.bind(data_shapes=tr_iter.provide_data, label_shapes=tr_iter.provide_label)
init = mx.initializer.Mixed(['fcout_bias', '.*'], [mx.init.Normal(0.01), mx.init.Normal(0.01)])
model.init_params(initializer=init)
model.init_optimizer(optimizer='Adam',optimizer_params=(('learning_rate', 0.001),('clip_gradient',1),))

The entire code runs fine with v0.9.3, but 0.10 throws this error. My current solution is to use 0.9.3 itself, but I think this is a pretty important issue that needs to be sorted out.

**Comment by chunyang-wen** [comment]
Interested things found on [SO](https://stackoverflow.com/questions/41117740/tensorflow-crashes-with-cublas-status-alloc-failed)

Maybe there are memory issues or any improving actions need to be taken.

**Comment by nikrao** [comment]
Are there plans to have a patch or something for mxnet?

**Comment by nikrao** [comment]
and to add: is there a corresponding fix for mxnet? something like tf.config() in the SO link you pointed me to?

**Comment by Ldpe2G** [comment]
@nikrao are you using the lastest cuda 8? if not try upgrad cuda. It may solve the problem i guess.

**Comment by nikrao** [comment]
I was using the AWS Deep Learning AMI Ubuntu.

**Comment by nikrao** [comment]
@tqchen  any idea if this is fixed in the AMI or the latest version?

**Comment by sandeep-krishnamurthy** [comment]
@nikrao 
1) Latest AMI as of today has MXNet v0.10. Hence, fix is not available yet. We will plan to release a new AMI in next 1 week with the fixes on v0.10. Also, publish Instructions to patch an older AMI.

2) Can you try to build from the latest master and see if this issue is still reproducible?

3) Is it possible to share the code snippet you used?

**Comment by nikrao** [comment]
Let me try 2. If that does not work, I'll share a snippet.

**Comment by nikrao** [comment]
OK, looks like the issue has been fixed in the latest build.
