### ISSUE TITLE
predict using ctx=gpu is not working

### ISSUE THREAD

**Issue by kimtang** [dmlc/mxnet#6749]
Hi all,

I loaded a model using mx.model.load and wanted to apply predict with ctx=mx.gpu(0) but got the error below.

Is prediction using gpu working? When switching to default cpu everything is working.

Kim

For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Win64

Compiler: Mixed of MingW and msvc 8.0

Package used (Python/R/Scala/Julia): R

MXNet version: 

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): b35dc5645b64cc9834b76cd6f4d833fddb3017dd

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:
 version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

## Error Message:
Please paste the full error message, including stack trace.

[13:18:58] C:\dev\mxnet\buildLibrary\mxnet\dmlc-core\include\dmlc/logging.h:304: [13:18:58] c:\dev\mxnet\buildlibrary\mxnet\src\operator\./cudnn_convolution-inl.h:613: Check failed: e == CUDNN_STATUS_SUCCESS (4 vs. 0) cuDNN: CUDNN_STATUS_INTERNAL_ERROR
[13:18:58] C:\dev\mxnet\buildLibrary\mxnet\dmlc-core\include\dmlc/logging.h:304: [13:18:58] c:\dev\mxnet\buildlibrary\mxnet\src\engine\./threaded_engine.h:329: [13:18:58] c:\dev\mxnet\buildlibrary\mxnet\src\operator\./cudnn_convolution-inl.h:613: Check failed: e == CUDNN_STATUS_SUCCESS (4 vs. 0) cuDNN: CUDNN_STATUS_INTERNAL_ERROR
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

***Repl Closed***

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by yuconglin** [comment]
can you try some simple example codes first:

import mxnet as mx
a = mx.nd.ones((2, 3), mx.gpu())
b = a * 2 + 1
b.asnumpy()

does this work?

**Comment by kimtang** [comment]
I mainly use R

 

And yes the code is working.

 

Kim

 

> library(mxnet)

> a = mx.nd.ones(c(2, 3), mx.gpu())

> b = a * 2 + 1

> as.array(b)

     [,1] [,2] [,3]

[1,]    3    3    3

[2,]    3    3    3

>

**Comment by thirdwing** [comment]
I think the prediction with `mx.gpu()` works on Linux.

Did you compile the pkg by yourself or use the prebuilt pkg provided by us?

**Comment by kimtang** [comment]
I compiled everything by myself using msvc 8 and mingw64 for r build.

Kim

**Comment by thirdwing** [comment]
Can you try the prebuilt pkg?

```r
cran <- getOption("repos")
cran["dmlc"] <- "https://s3.amazonaws.com/mxnet-r/GPU"
options(repos = cran)
install.packages("mxnet")
```

**Comment by kimtang** [comment]
I found the problem. Arguments wrongly passed to prediction. Sorry for the noise
